"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'ClassicCars',
        # If MongoDB is running on localhost, you can omit HOST and PORT
        'HOST': 'mongodb://localhost:27017', # or your MongoDB Atlas URI
        'USER': '',    # Your MongoDB username, if required
        'PASSWORD': '',  # Your MongoDB password, if required
    }
}

INSTALLED_APPS = [
    # ... other installed apps ...
    'corsheaders',
]
MIDDLEWARE = [
    # ... other middleware ...
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # ... other middleware ...
]

CORS_ALLOW_ALL_ORIGINS = True


ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CORS_ORIGIN_WHITELIST = [
    'https://localhost:7210',
]
